language: node_js

node_js:
  - '12'

install:
  - yarn --frozen-lockfile

script:
  - yarn run lint
  - yarn run test
  - cd examples
  - yarn build
  - cd ..

after_success:
  - yarn run coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && yarn run semantic-release'
    on:
      all_branches: true # semantic release handles tht for us
  - provider: pages
    local_dir: examples/build
    skip_cleanup: true
    target_branch: main
    repo: react-page/react-page.github.io
    github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
    on:
      branch: master
  - provider: pages
    local_dir: examples/build
    skip_cleanup: true
    target_branch: main
    repo: react-page/next
    github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
    on:
      branch: next
